spring:
  application:
    name: token-service
  datasource:
    url: ${TOKEN_SERVICE_DATABASE_URL}
    username: ${TOKEN_SERVICE_DATABASE_USERNAME}
    password: ${TOKEN_SERVICE_DATABASE_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true

token:
  expiration-time: 86400 # 24 hours

user-service:
  url: ${USER_SERVICE_URL}

server:
  port: 8082
