spring:
  application:
    name: token-service
  datasource:
    url: ${TOKEN_SERVICE_DATABASE_URL}
    username: ${TOKEN_SERVICE_DATABASE_USERNAME}
    password: ${TOKEN_SERVICE_DATABASE_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace